// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbwrocgfsquuxkomrijh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZid3JvY2dmc3F1dXhrb21yaWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Nzc3OTYsImV4cCI6MjA2OTM1Mzc5Nn0.07gcX6ZvU0K92IVBaPz54kXuGVArxruJSd_hRJS0Qnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});